# Site settings
title: Suyoung Lee
description: Suyoung Lee / 이수영. Ph.D. student @KAIST WSP Lab.
url: https://leeswimming.com
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Daejun Kim
user_title: Security Researcher
user_description: >
  I am a security researcher who is interested in the security of the Internet.
email: reset@theori.io
# twitter: lorem_ipsum
github: Reset-Kim
facebook: reset.test
# gplus_username:  lorem_ipsum
