# Site settings
title: Daejun Kim
description: Daejun Kim / 김대준
url: https://reset-kim.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Daejun Kim
user_title: Security Researcher
user_description: >
  I am a security researcher who is interested in cyber security.
  My primary research interests lie in finding, analyzing, and patching software vulnerabilities.
  In particular, I am interested in these areas: Blockchain, Web, and System security.
  Also, I've found hundreds of high-impact vulnerabilities while conducting security auditing projects so far.
email: reset@theori.io
# twitter: lorem_ipsum
github: Reset-Kim
facebook: reset.test
# gplus_username:  lorem_ipsum
